ARG EMSCRIPTEN_TAG=1.37.39
FROM ricejasonf/emscripten_fastcomp:$EMSCRIPTEN_TAG
  ARG EMSCRIPTEN_TAG

  RUN apt-get update && apt-get -y install \
    python default-jre-headless curl tar xz-utils build-essential \
      cmake git autoconf bash-completion vim python \
    && echo '. /usr/share/bash-completion/bash_completion && set -o vi' >> /root/.bashrc \
    && echo 'set hlsearch' >> /root/.vimrc

  WORKDIR /usr/local/src

  # node
  RUN curl -O https://nodejs.org/dist/v6.9.5/node-v6.9.5-linux-x64.tar.xz \
   && tar -xvf node-v6.9.5-linux-x64.tar.xz \
   && cp -r node-v6.9.5-linux-x64/* /usr/local/ \
   && rm -f node-v6.9.5-linux-x64.tar.xz \
   && rm -rf node-v6.9.5-linux-x64

  # Emscripten SDK
  RUN git clone --depth 1 -b $EMSCRIPTEN_TAG https://github.com/kripken/emscripten.git \
   && rm -rf emscripten/tests

  WORKDIR /usr/local/src/emscripten
  RUN ./emcc -v \
   && ./embuilder.py build ALL

  ENV CC=/usr/local/bin/clang \
      CXX=/usr/local/bin/clang++ \
      LD_LIBRARY_PATH=/usr/local/lib \
      EMCC_SKIP_SANITY_CHECK=1

  RUN echo 'export EMCC_SKIP_SANITY_CHECK=1' >> /root/.bashrc
