ARG EMSCRIPTEN_TAG=1.37.39
FROM ubuntu:bionic as fastcomp_build
  ARG EMSCRIPTEN_TAG

  RUN apt-get update && apt-get -y install curl tar git cmake build-essential python

  RUN git clone --depth 1 \
                -b $EMSCRIPTEN_TAG \
                https://github.com/kripken/emscripten-fastcomp.git \
   && cd emscripten-fastcomp/tools/ \
   && git clone --depth 1 \
                -b $EMSCRIPTEN_TAG \
                https://github.com/kripken/emscripten-fastcomp-clang.git clang \
   && cd ../projects \
   && git clone --depth 1 https://github.com/llvm-mirror/libcxx.git \
   && git clone --depth 1 https://github.com/llvm-mirror/libcxxabi.git \
   && cd ../ && mkdir build && cd build \
   && cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
      -DLLVM_TARGETS_TO_BUILD="X86;ARM;JSBackend" \
      -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF \
      -DCLANG_INCLUDE_EXAMPLES=OFF -DCLANG_INCLUDE_TESTS=OFF \
      .. \
   && make -j4 && make install

FROM ubuntu:bionic

  COPY --from=fastcomp_build /usr/local/lib /usr/local/lib
  COPY --from=fastcomp_build /usr/local/include /usr/local/include
  COPY --from=fastcomp_build /usr/local/bin /usr/local/bin
