ARG EMSCRIPTEN_TAG=1.38.25
FROM ricejasonf/emscripten_fastcomp:$EMSCRIPTEN_TAG
  ARG EMSCRIPTEN_TAG

  RUN apt-get update && apt-get -y install \
    python default-jre-headless nodejs npm build-essential \
      cmake git autoconf bash-completion vim python \
    && echo '. /usr/share/bash-completion/bash_completion && set -o vi' >> /root/.bashrc \
    && echo 'set hlsearch' >> /root/.vimrc

  WORKDIR /usr/local/src

  # Emscripten SDK
  RUN git clone --depth 1 -b $EMSCRIPTEN_TAG https://github.com/kripken/emscripten.git \
   && rm -rf emscripten/tests

  WORKDIR /usr/local/src/emscripten
  RUN ./emcc -v \
   && ./embuilder.py build ALL

  ENV CC=/usr/local/bin/clang \
      CXX=/usr/local/bin/clang++ \
      LD_LIBRARY_PATH=/usr/local/lib \
      EMCC_SKIP_SANITY_CHECK=1

  RUN echo 'export EMCC_SKIP_SANITY_CHECK=1' >> /root/.bashrc
