FROM ubuntu:artful as fastcomp_build

  ENV USE_EMSCRIPTEN_TAG=1.37.19

  RUN apt-get update && apt-get -y install git cmake build-essential python

  RUN git clone -b $USE_EMSCRIPTEN_TAG https://github.com/kripken/emscripten-fastcomp.git \
    && cd emscripten-fastcomp/tools/ \
    && git clone -b $USE_EMSCRIPTEN_TAG https://github.com/kripken/emscripten-fastcomp-clang.git clang \
    && cd ../projects \
    && git clone https://github.com/llvm-mirror/libcxx.git \
    && git clone https://github.com/llvm-mirror/libcxxabi.git \
    && cd ../ && mkdir build && cd build \
    && cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
      -DLLVM_TARGETS_TO_BUILD="X86;ARM;JSBackend" \
      -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF \
      -DCLANG_INCLUDE_EXAMPLES=OFF -DCLANG_INCLUDE_TESTS=OFF \
      .. \
    && make -j4 && make install

FROM ubuntu:artful

  COPY --from=fastcomp_build /usr/local/lib /usr/local/lib
  COPY --from=fastcomp_build /usr/local/include /usr/local/include
  COPY --from=fastcomp_build /usr/local/bin /usr/local/bin
